// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBqr77FBjLIPxRYm4R54RZHQUgEQ_mXc',
    appId: '1:1055927179578:web:ee2d78538dd4421d60d803',
    messagingSenderId: '1055927179578',
    projectId: 'briefcase-546db',
    authDomain: 'briefcase-546db.firebaseapp.com',
    storageBucket: 'briefcase-546db.firebasestorage.app',
    measurementId: 'G-P2GYZEH06Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-ZITdpu_FjAiABu688Mf8GurQ4CdVxE',
    appId: '1:1055927179578:android:88c7598bbe1e101d60d803',
    messagingSenderId: '1055927179578',
    projectId: 'briefcase-546db',
    storageBucket: 'briefcase-546db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCc_H9-ig0noGsYgjUwag4H8GyDk0YbD4',
    appId: '1:1055927179578:ios:9bbdc58988b4eecd60d803',
    messagingSenderId: '1055927179578',
    projectId: 'briefcase-546db',
    storageBucket: 'briefcase-546db.firebasestorage.app',
    iosBundleId: 'com.example.briefcaseSport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCc_H9-ig0noGsYgjUwag4H8GyDk0YbD4',
    appId: '1:1055927179578:ios:9bbdc58988b4eecd60d803',
    messagingSenderId: '1055927179578',
    projectId: 'briefcase-546db',
    storageBucket: 'briefcase-546db.firebasestorage.app',
    iosBundleId: 'com.example.briefcaseSport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBqr77FBjLIPxRYm4R54RZHQUgEQ_mXc',
    appId: '1:1055927179578:web:e50efc1d0fca7e5f60d803',
    messagingSenderId: '1055927179578',
    projectId: 'briefcase-546db',
    authDomain: 'briefcase-546db.firebaseapp.com',
    storageBucket: 'briefcase-546db.firebasestorage.app',
    measurementId: 'G-9LJXBF9JK2',
  );

}